[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#static"

[functions]
  node_bundler = "esbuild"
  
[functions.generate-website]
  timeout = 30  # Increase timeout to 30 seconds